---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: trusty
inputs:
  - name: app-src
outputs:
  - name: manifests
run:
  path: app-src/ci/tasks/build-manifest.sh
params:
  application_name:     replace-me
  num_instances:        replace-me
