---
groups:
  - name: emcworld-demo
    jobs:
      - unit-tests
      - deploy-to-dev-tenant1
      - deploy-to-qa-tenant1
      - deploy-to-prod-tenant2

jobs:
  - name: unit-tests
    public: true
    plan:
      - aggregate:
        - {trigger: true, get: app-src}

      - task: unit-tests
        file: app-src/ci/tasks/unit-tests.yml

  - name: deploy-to-dev-tenant1
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [unit-tests], get: app-src}
        - {trigger: false,                       get: app-version, params: {bump: patch}}

      - put: app-version
        params: {file: app-version/number}

      - task: build-dev-manifest
        file: app-src/ci/tasks/build-manifest.yml
        config:
          params:
            application_name:     {{dev-tenant1_application_name}}
            num_instances:        {{dev-tenant1_num_instances}}
            SPRING_PROFILES_ACTIVE:                cloud

      - put: pcf-dev-tenant1
        params:
          manifest: manifests/manifest-dev-tenant1.yml
          path: app-src/cities/cities-service
          current_app_name: {{dev-tenant1_application_name}}

  - name: deploy-to-qa-tenant1
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [unit-tests], get: app-src}
        - {trigger: false,                       get: app-version, params: {bump: patch}}

      - put: app-version
        params: {file: app-version/number}

      - task: build-qa-manifest
        file: app-src/ci/tasks/build-manifest.yml
        config:
          params:
            application_name:     {{qa-tenant1_application_name}}
            num_instances:        {{qa-tenant1_num_instances}}
            SPRING_PROFILES_ACTIVE:                cloud

      - put: pcf-qa-tenant1
        params:
          manifest: manifests/manifest-qa-tenant1.yml
          path: app-src/cities/cities-service
          current_app_name: {{qa-tenant1_application_name}}

  - name: deploy-to-prod-tenant2
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [unit-tests], get: app-src}
        - {trigger: false,                       get: app-version, params: {bump: patch}}

      - put: app-version
        params: {file: app-version/number}

      - task: build-prod-manifest
        file: app-src/ci/tasks/build-manifest.yml
        config:
          params:
            application_name:     {{prod-tenant2_application_name}}
            num_instances:        {{prod-tenant2_num_instances}}
            SPRING_PROFILES_ACTIVE:                cloud

      - put: pcf-qa-tenant1
        params:
          manifest: manifests/manifest-prod-tenant1.yml
          path: app-src/cities/cities-service
          current_app_name: {{prod-tenant2_application_name}}


resources:
  - name: app-src
    type: git
    source:
      uri: git@github.com:boparp-pivotal/emcworld-pcf-photon-demo.git
      branch: master

  - name: app-version
    type: semver
    source:
      key:               current-version

  - name: pcf-dev-tenant1
    type: cf
    source:
      api: {{dev-tenant1_cf_api}}
      username: {{dev-tenant1_cf_username}}
      password: {{dev-tenant1_cf_password}}
      organization: {{dev-tenant1_cf_org}}
      space: {{dev-tenant1_cf_space}}
      skip_cert_check: true

  - name: pcf-qa-tenant1
    type: cf
    source:
      api: {{qa-tenant1_cf_api}}
      username: {{qa-tenant1_cf_username}}
      password: {{qa-tenant1_cf_password}}
      organization: {{qa-tenant1_cf_org}}
      space: {{qa-tenant1_cf_space}}
      skip_cert_check: true

  - name: pcf-prod-tenant2
    type: cf
    source:
      api: {{prod-tenant2_cf_api}}
      username: {{prod-tenant2_cf_username}}
      password: {{prod-tenant2_cf_password}}
      organization: {{prod-tenant2_cf_org}}
      space: {{prod-tenant2_cf_space}}
      skip_cert_check: true
